import { createMcpHandler } from "mcp-handler";
import { z } from "zod";

export const runtime="nodejs"; export const maxDuration=60;
const ORIGIN=process.env.RMF_PUBLIC_ORIGIN||"https://ratemyface.vercel.app";
async function control(action:string,url?:string){const secret=process.env.RMF_BROWSER_AGENT_SECRET||"";if(!secret)throw new Error("RMF_BROWSER_AGENT_SECRET_not_configured");const r=await fetch(`${ORIGIN}/api/operator/browser-control`,{method:"POST",headers:{"content-type":"application/json","x-rmf-browser-agent":secret},body:JSON.stringify({action,...(url?{url}:{})}),cache:"no-store"});const text=await r.text();if(!r.ok)throw new Error(`browser_control_${r.status}:${text.slice(0,1000)}`);try{return JSON.parse(text)}catch{return{raw:text}}}
const out=(x:unknown)=>({content:[{type:"text" as const,text:JSON.stringify(x)}],structuredContent:x as Record<string,unknown>});
const mcpHandler=createMcpHandler(server=>{
 const ro={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:true};
 server.registerTool("browser_health",{title:"Persistent Browser Health",description:"Check the Vercel-to-Railway persistent browser runtime.",inputSchema:{},annotations:ro},async()=>out(await control("status")));
 server.registerTool("chatgpt_observe_closure",{title:"ChatGPT Observe Closure",description:"Observe an allowlisted ChatGPT HTTPS page through Railway Chromium, independently reread it, compare snapshot digests, and halt without account mutation.",inputSchema:{url:z.string().url().optional()},annotations:ro},async({url})=>{const target=url||"https://chatgpt.com/";const observation=await control("observe",target);const receipt=await control("receipt");return out({ok:Boolean(observation?.ok&&receipt?.ok&&receipt?.digest_match),target,observation,receipt,closure:{digest_match:Boolean(receipt?.digest_match),halted:Boolean(receipt?.halted)}})});
 server.registerTool("browser_session",{title:"Browser Session State",description:"Check persistent site state for an allowed HTTPS URL.",inputSchema:{url:z.string().url()},annotations:ro},async({url})=>out(await control("session",url)));
 server.registerTool("browser_observe",{title:"Observe Browser Page",description:"Navigate to an allowed HTTPS URL and return its current URL, title, text snapshot and digest.",inputSchema:{url:z.string().url()},annotations:ro},async({url})=>out(await control("observe",url)));
 server.registerTool("browser_receipt",{title:"Browser Verification Receipt",description:"Independently reread the browser page and return a digest-match receipt.",inputSchema:{url:z.string().url().optional()},annotations:ro},async({url})=>out(await control("receipt",url)));
 server.registerTool("browser_navigate",{title:"Navigate Browser",description:"Navigate the persistent Railway browser to an allowed HTTPS URL.",inputSchema:{url:z.string().url()},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async({url})=>out(await control("navigate",url)));
 server.registerTool("browser_owner_start",{title:"Start Interactive Browser",description:"Start a short-lived interactive viewer for the persistent Railway browser.",inputSchema:{url:z.string().url().optional()},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async({url})=>out(await control("ownerStart",url)));
 server.registerTool("browser_owner_status",{title:"Interactive Browser Status",description:"Check whether the temporary interactive viewer is active.",inputSchema:{},annotations:ro},async()=>out(await control("ownerStatus")));
 server.registerTool("browser_owner_finish",{title:"Finish Interactive Browser",description:"Finish the temporary viewer while retaining the persistent profile.",inputSchema:{},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false}},async()=>out(await control("ownerFinish")));
},{},{basePath:"/api",maxDuration:60,verboseLogs:false});
function authorized(request:Request){const expected=process.env.RMF_CHATGPT_MCP_TOKEN||"";if(!expected)return true;return request.headers.get("authorization")===`Bearer ${expected}`}
async function guarded(request:Request){if(!authorized(request))return new Response(JSON.stringify({error:"unauthorized"}),{status:401,headers:{"content-type":"application/json"}});return mcpHandler(request)}
export {guarded as GET,guarded as POST,guarded as DELETE};
