import express from "express";
import { chromium } from "playwright";
import crypto from "node:crypto";
import http from "node:http";
import httpProxy from "http-proxy";
import { spawn, execFileSync } from "node:child_process";
import fs from "node:fs";
import net from "node:net";

const app=express(); app.use(express.json({limit:"64kb"}));
const server=http.createServer(app),proxy=httpProxy.createProxyServer({target:"http://127.0.0.1:6080",ws:true});
const PORT=Number(process.env.PORT||8080),TOKEN=process.env.RMF_BROWSER_CONTROL_TOKEN||"",GRANT_SECRET=process.env.RMF_BROWSER_GRANT_SECRET||"",PROFILE=process.env.RMF_BROWSER_PROFILE_DIR||"/data/browser-profile",EXECUTABLE=process.env.RMF_BROWSER_EXECUTABLE||"/usr/bin/google-chrome";
const ALLOWED=new Set((process.env.RMF_BROWSER_ALLOWED_HOSTS||"chatgpt.com").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean)),OWNER_VERIFY_URL="https://ratemyface.vercel.app/api/operator/owner";
let context=null,ownerSession=null,vncProcess=null,websockifyProcess=null,expiryTimer=null;
function safeEqual(a,b){const x=Buffer.from(a||""),y=Buffer.from(b||"");return x.length===y.length&&crypto.timingSafeEqual(x,y)} function timingMatch(h){return TOKEN&&safeEqual(h,`Bearer ${TOKEN}`)}
function grantValid(req){if(!GRANT_SECRET)return false;const [body,sig,...rest]=String(req.headers["x-rmf-browser-grant"]||"").split(".");if(!body||!sig||rest.length)return false;const expected=crypto.createHmac("sha256",GRANT_SECRET).update(body).digest("base64url");if(!safeEqual(sig,expected))return false;try{const p=JSON.parse(Buffer.from(body,"base64url").toString("utf8")),now=Math.floor(Date.now()/1000);return p?.aud==="rmf-browser-runtime"&&Number(p?.iat)<=now+30&&Number(p?.exp)>now&&Array.isArray(p?.scope)&&p.scope.length>0}catch{return false}}
async function ownerTokenValid(req){const t=String(req.headers["x-rmf-owner-access"]||req.cookies?.rmf_owner_access||"");if(!t)return false;try{const r=await fetch(OWNER_VERIFY_URL,{headers:{cookie:`rmf_owner_access=${encodeURIComponent(t)}`},redirect:"manual"}),b=r.ok?await r.json().catch(()=>null):null;return Boolean(b?.ok&&b?.owner?.id)}catch{return false}} async function guard(req,res,next){if(timingMatch(req.headers.authorization)||grantValid(req)||await ownerTokenValid(req))return next();res.status(401).json({ok:false,error:"unauthorized"})}
function allowedUrl(raw){const u=new URL(raw);if(u.protocol!=="https:")throw new Error("https_required");const h=u.hostname.toLowerCase();if(![...ALLOWED].some(x=>h===x||h.endsWith(`.${x}`)))throw new Error("host_not_allowed");return u.toString()}
async function browser(){if(!context){if(!fs.existsSync(EXECUTABLE))throw new Error(`chrome_not_found:${EXECUTABLE}`);context=await chromium.launchPersistentContext(PROFILE,{executablePath:EXECUTABLE,headless:false,args:["--no-sandbox","--disable-dev-shm-usage","--window-size=1440,900"]})}return context} async function page(){const c=await browser();return c.pages()[0]||await c.newPage()}
function digest(s){return crypto.createHash("sha256").update(s).digest("hex")} function clean(t){return String(t||"").replace(/Bearer\s+[A-Za-z0-9._~+\/-]+/gi,"Bearer [REDACTED]").replace(/\b(?:sk|sess)-[A-Za-z0-9_-]{12,}\b/g,"[REDACTED]").slice(0,50000)} function stopProc(p){try{if(p&&!p.killed)p.kill("SIGTERM")}catch{}}
async function waitForPort(port,timeoutMs=5000){const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){const open=await new Promise(resolve=>{const socket=net.createConnection({host:"127.0.0.1",port});let settled=false;const finish=value=>{if(settled)return;settled=true;socket.destroy();resolve(value)};socket.setTimeout(250);socket.once("connect",()=>finish(true));socket.once("error",()=>finish(false));socket.once("timeout",()=>finish(false))});if(open)return;await new Promise(resolve=>setTimeout(resolve,100))}throw new Error(`port_not_ready:${port}`)}
function endOwnerSession(){if(expiryTimer){clearTimeout(expiryTimer);expiryTimer=null}stopProc(websockifyProcess);stopProc(vncProcess);websockifyProcess=null;vncProcess=null;try{fs.unlinkSync("/tmp/rmf-vnc.pass")}catch{}ownerSession=null}
async function startOwnerSession(target="https://chatgpt.com/"){endOwnerSession();await new Promise(resolve=>setTimeout(resolve,200));const p=await page();try{await p.goto(allowedUrl(target),{waitUntil:"domcontentloaded",timeout:30000})}catch{}const password=crypto.randomBytes(6).toString("base64url").slice(0,8);execFileSync("x11vnc",["-storepasswd",password,"/tmp/rmf-vnc.pass"],{stdio:"ignore"});vncProcess=spawn("x11vnc",["-display",process.env.DISPLAY||":99","-rfbauth","/tmp/rmf-vnc.pass","-rfbport","5900","-localhost","-forever","-shared","-noxdamage"],{stdio:"ignore"});await waitForPort(5900);websockifyProcess=spawn("websockify",["--web=/usr/share/novnc","6080","127.0.0.1:5900"],{stdio:"ignore"});await waitForPort(6080);const sessionToken=crypto.randomBytes(24).toString("base64url"),expiresAt=Date.now()+15*60*1000;ownerSession={sessionToken,password,expiresAt};expiryTimer=setTimeout(endOwnerSession,15*60*1000);return{session_token:sessionToken,vnc_password:password,expires_at:new Date(expiresAt).toISOString(),viewer_path:`/owner-browser/session?token=${encodeURIComponent(sessionToken)}`}}
function viewerValid(req){return Boolean(ownerSession&&Date.now()<=ownerSession.expiresAt&&req.cookies?.rmf_browser_view===ownerSession.sessionToken)} async function snapshotCurrent(){const p=await page(),title=await p.title(),text=clean(await p.locator("body").innerText({timeout:10000})),final_url=p.url();return{final_url,title,text,snapshot_digest:digest(JSON.stringify({final_url,title,text}))}}
async function siteState(raw){const target=allowedUrl(raw),u=new URL(target),c=await browser(),cookies=await c.cookies(target),p=await page();if(p.url()!==target)await p.goto(target,{waitUntil:"domcontentloaded",timeout:30000});const body=clean(await p.locator("body").innerText({timeout:8000}).catch(()=>""));return{host:u.hostname,current_url:p.url(),title:await p.title().catch(()=>""),cookie_count:cookies.length,has_persistent_site_state:cookies.length>0,login_required:/\b(log in|sign in|sign up|continue with google)\b/i.test(body)&&cookies.length===0,profile_dir:PROFILE,browser_product:"Google Chrome",browser_executable:EXECUTABLE}}
async function logoutSite(raw){const target=allowedUrl(raw),u=new URL(target),c=await browser(),cookies=await c.cookies(target);if(cookies.length)await c.clearCookies({domain:u.hostname});return{host:u.hostname,cleared_cookie_count:cookies.length}}
app.use((req,_res,next)=>{const raw=String(req.headers.cookie||"");req.cookies=Object.fromEntries(raw.split(";").map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf("=");return[decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}));next()});app.get("/health",(_req,res)=>res.json({ok:true,browser:"google-chrome"}));
app.get("/health-detailed",guard,async(_req,res)=>{try{const p=await page();res.json({ok:true,runtime:"railway-playwright-google-chrome",browser_executable:EXECUTABLE,persistent_profile:true,profile_dir:PROFILE,current_url:p.url(),allowed_hosts:[...ALLOWED],interactive_login_active:Boolean(ownerSession)})}catch(e){res.status(503).json({ok:false,error:String(e?.message||e)})}});app.get("/session-state",guard,async(req,res)=>{try{res.json({ok:true,...await siteState(String(req.query.url||"https://chatgpt.com/"))})}catch(e){res.status(400).json({ok:false,error:String(e?.message||e)})}});app.get("/login-required",guard,async(req,res)=>{try{const s=await siteState(String(req.query.url||""));res.json({ok:true,host:s.host,login_required:s.login_required,has_persistent_site_state:s.has_persistent_site_state})}catch(e){res.status(400).json({ok:false,error:String(e?.message||e)})}});
app.post("/navigate",guard,async(req,res)=>{try{const url=allowedUrl(String(req.body?.url||"")),p=await page();await p.goto(url,{waitUntil:"domcontentloaded",timeout:30000});res.json({ok:true,final_url:p.url(),title:await p.title(),site_state:await siteState(url)})}catch(e){res.status(400).json({ok:false,error:String(e?.message||e)})}});app.post("/observe",guard,async(req,res)=>{try{const url=allowedUrl(String(req.body?.url||"")),p=await page();await p.goto(url,{waitUntil:"domcontentloaded",timeout:30000});res.json({ok:true,...await snapshotCurrent(),site_state:await siteState(url)})}catch(e){res.status(400).json({ok:false,error:String(e?.message||e)})}});app.post("/receipt",guard,async(req,res)=>{try{const p=await page();if(req.body?.url)await p.goto(allowedUrl(String(req.body.url)),{waitUntil:"domcontentloaded",timeout:30000});let a=await snapshotCurrent(),b=a,attempts=0;for(;attempts<12;attempts++){await p.waitForTimeout(500);b=await snapshotCurrent();if(a.snapshot_digest===b.snapshot_digest)break;a=b}res.json({ok:true,halted:true,digest_match:a.snapshot_digest===b.snapshot_digest,first_digest:a.snapshot_digest,second_digest:b.snapshot_digest,stability_attempts:attempts+1,final_url:b.final_url,title:b.title})}catch(e){res.status(400).json({ok:false,error:String(e?.message||e)})}});app.post("/logout-site",guard,async(req,res)=>{try{res.json({ok:true,...await logoutSite(String(req.body?.url||""))})}catch(e){res.status(400).json({ok:false,error:String(e?.message||e)})}});
app.post("/owner-session/start",guard,async(req,res)=>{try{res.json({ok:true,...await startOwnerSession(String(req.body?.url||"https://chatgpt.com/"))})}catch(e){endOwnerSession();res.status(500).json({ok:false,error:String(e?.message||e)})}});app.get("/owner-session/status",guard,(_req,res)=>res.json({ok:true,active:Boolean(ownerSession),expires_at:ownerSession?new Date(ownerSession.expiresAt).toISOString():null,persistent_profile:true}));app.post("/owner-session/finish",guard,(_req,res)=>{endOwnerSession();res.json({ok:true,finished:true,persistent_profile_retained:true})});
app.get("/owner-browser/session",(req,res)=>{const token=String(req.query.token||"");if(!ownerSession||token!==ownerSession.sessionToken||Date.now()>ownerSession.expiresAt)return res.status(401).send("Invalid or expired browser session.");res.cookie("rmf_browser_view",token,{httpOnly:true,secure:true,sameSite:"none",partitioned:true,path:"/owner-browser",maxAge:15*60*1000});res.redirect(`/owner-browser/vnc.html?autoconnect=true&reconnect=true&reconnect_delay=1000&shared=true&resize=scale&path=owner-browser/websockify#password=${encodeURIComponent(ownerSession.password)}`)});app.use("/owner-browser",(req,res)=>{if(!viewerValid(req))return res.status(401).send("Temporary browser login session is not active.");req.url=req.url.replace(/^\/owner-browser/,"")||"/";proxy.web(req,res)});server.on("upgrade",(req,socket,head)=>{if(!req.url?.startsWith("/owner-browser/")){socket.destroy();return}const raw=String(req.headers.cookie||""),cookies=Object.fromEntries(raw.split(";").map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf("=");return[decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}));if(!ownerSession||cookies.rmf_browser_view!==ownerSession.sessionToken||Date.now()>ownerSession.expiresAt){socket.destroy();return}req.url=req.url.replace(/^\/owner-browser/,"")||"/";proxy.ws(req,socket,head)});server.listen(PORT,"0.0.0.0",()=>console.log(`browser runtime listening ${PORT} using ${EXECUTABLE}`));