import express from "express";
import { chromium } from "playwright";
import crypto from "node:crypto";
import http from "node:http";
import httpProxy from "http-proxy";
import { spawn, execFileSync } from "node:child_process";
import fs from "node:fs";

const app=express(); app.use(express.json({limit:"64kb"}));
const server=http.createServer(app);
const proxy=httpProxy.createProxyServer({target:"http://127.0.0.1:6080",ws:true});
const PORT=Number(process.env.PORT||8080);
const TOKEN=process.env.RMF_BROWSER_CONTROL_TOKEN||"";
const GRANT_SECRET=process.env.RMF_BROWSER_GRANT_SECRET||"";
const PROFILE=process.env.RMF_BROWSER_PROFILE_DIR||"/data/browser-profile";
const ALLOWED=new Set((process.env.RMF_BROWSER_ALLOWED_HOSTS||"chatgpt.com").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean));
const OWNER_VERIFY_URL="https://ratemyface.vercel.app/api/operator/owner";
let context=null,ownerSession=null,vncProcess=null,websockifyProcess=null,expiryTimer=null;
function timingMatch(h){if(!TOKEN)return false;const a=Buffer.from(h||""),b=Buffer.from(`Bearer ${TOKEN}`);return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function safeEqual(a,b){const x=Buffer.from(a||""),y=Buffer.from(b||"");return x.length===y.length&&crypto.timingSafeEqual(x,y);}
function grantValid(req){if(!GRANT_SECRET)return false;const raw=String(req.headers["x-rmf-browser-grant"]||"");const [body,sig,...rest]=raw.split(".");if(!body||!sig||rest.length)return false;const expected=crypto.createHmac("sha256",GRANT_SECRET).update(body).digest("base64url");if(!safeEqual(sig,expected))return false;try{const p=JSON.parse(Buffer.from(body,"base64url").toString("utf8"));const now=Math.floor(Date.now()/1000);return p?.aud==="rmf-browser-runtime"&&Number(p?.iat)<=now+30&&Number(p?.exp)>now&&Array.isArray(p?.scope)&&p.scope.length>0;}catch{return false;}}
async function ownerTokenValid(req){const headerToken=String(req.headers["x-rmf-owner-access"]||"");const cookieToken=String(req.cookies?.rmf_owner_access||"");const t=headerToken||cookieToken;if(!t)return false;try{const r=await fetch(OWNER_VERIFY_URL,{headers:{cookie:`rmf_owner_access=${encodeURIComponent(t)}`},redirect:"manual"});if(!r.ok)return false;const b=await r.json().catch(()=>null);return Boolean(b?.ok&&b?.owner?.id);}catch{return false;}}
async function guard(req,res,next){if(timingMatch(req.headers.authorization))return next();if(grantValid(req))return next();if(await ownerTokenValid(req))return next();return res.status(401).json({ok:false,error:"unauthorized"});}
function allowedUrl(raw){const u=new URL(raw);if(u.protocol!=="https:")throw new Error("https_required");const h=u.hostname.toLowerCase();if(![...ALLOWED].some(x=>h===x||h.endsWith(`.${x}`)))throw new Error("host_not_allowed");return u.toString();}
async function browser(){if(!context)context=await chromium.launchPersistentContext(PROFILE,{headless:false,args:["--no-sandbox","--disable-dev-shm-usage","--window-size=1440,900"]});return context;}
async function page(){const c=await browser();return c.pages()[0]||await c.newPage();}
function digest(s){return crypto.createHash("sha256").update(s).digest("hex");}
function clean(t){return String(t||"").replace(/Bearer\s+[A-Za-z0-9._~+\/-]+/gi,"Bearer [REDACTED]").replace(/\b(?:sk|sess)-[A-Za-z0-9_-]{12,}\b/g,"[REDACTED]").slice(0,50000);}
function stopProc(p){try{if(p&&!p.killed)p.kill("SIGTERM");}catch{}}
function endOwnerSession(){if(expiryTimer){clearTimeout(expiryTimer);expiryTimer=null;}stopProc(websockifyProcess);stopProc(vncProcess);websockifyProcess=null;vncProcess=null;try{fs.unlinkSync("/tmp/rmf-vnc.pass");}catch{}ownerSession=null;}
async function startOwnerSession(){endOwnerSession();const p=await page();try{await p.goto("https://chatgpt.com/",{waitUntil:"domcontentloaded",timeout:30000});}catch{}const password=crypto.randomBytes(6).toString("base64url").slice(0,8);execFileSync("x11vnc",["-storepasswd",password,"/tmp/rmf-vnc.pass"],{stdio:"ignore"});vncProcess=spawn("x11vnc",["-display",process.env.DISPLAY||":99","-rfbauth","/tmp/rmf-vnc.pass","-rfbport","5900","-localhost","-forever","-shared","-noxdamage"],{stdio:"ignore"});websockifyProcess=spawn("websockify",["--web=/usr/share/novnc","6080","127.0.0.1:5900"],{stdio:"ignore"});const sessionToken=crypto.randomBytes(24).toString("base64url"),expiresAt=Date.now()+15*60*1000;ownerSession={sessionToken,password,expiresAt};expiryTimer=setTimeout(endOwnerSession,15*60*1000);return{session_token:sessionToken,vnc_password:password,expires_at:new Date(expiresAt).toISOString(),viewer_path:`/owner-browser/session?token=${encodeURIComponent(sessionToken)}`};}
function viewerValid(req){if(!ownerSession||Date.now()>ownerSession.expiresAt)return false;return req.cookies?.rmf_browser_view===ownerSession.sessionToken;}
async function snapshotCurrent(){const p=await page();const title=await p.title();const text=clean(await p.locator("body").innerText({timeout:10000}));const final_url=p.url();const stable=JSON.stringify({final_url,title,text});return{final_url,title,text,snapshot_digest:digest(stable)};}
async function chatgptState(){const p=await page();const url=p.url();const title=await p.title().catch(()=>"");let authenticated=false;let evidence="unknown";try{const body=clean(await p.locator("body").innerText({timeout:8000}));const hasLogin=/\b(log in|sign up)\b/i.test(body);const hasComposer=await p.locator('textarea,[contenteditable="true"]').count().catch(()=>0)>0;authenticated=hasComposer&&!hasLogin;evidence=authenticated?"composer_present_no_login_prompt":hasLogin?"login_prompt_present":"indeterminate";}catch{}return{authenticated,evidence,current_url:url,title,profile_dir:PROFILE};}
app.use((req,_res,next)=>{const raw=String(req.headers.cookie||"");req.cookies=Object.fromEntries(raw.split(";").map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf("=");return[decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}));next();});
app.get("/health",(_req,res)=>res.status(200).json({ok:true}));
app.get("/health-detailed",guard,async(_req,res)=>{try{const p=await page();res.json({ok:true,runtime:"railway-playwright",session_attached:true,current_url:p.url(),allowed_hosts:[...ALLOWED],interactive_login_active:Boolean(ownerSession)});}catch(e){res.status(503).json({ok:false,error:String(e?.message||e)});}});
app.get("/session-state",guard,async(_req,res)=>{try{res.json({ok:true,...await chatgptState()});}catch(e){res.status(503).json({ok:false,error:String(e?.message||e)});}});
app.post("/navigate",guard,async(req,res)=>{try{const url=allowedUrl(String(req.body?.url||""));const p=await page();await p.goto(url,{waitUntil:"domcontentloaded",timeout:30000});res.json({ok:true,final_url:p.url(),title:await p.title()});}catch(e){res.status(400).json({ok:false,error:String(e?.message||e)});}});
app.post("/observe",guard,async(req,res)=>{try{const url=allowedUrl(String(req.body?.url||""));const p=await page();await p.goto(url,{waitUntil:"domcontentloaded",timeout:30000});res.json({ok:true,...await snapshotCurrent()});}catch(e){res.status(400).json({ok:false,error:String(e?.message||e)});}});
app.post("/receipt",guard,async(req,res)=>{try{const requested=req.body?.url?allowedUrl(String(req.body.url)):null;const p=await page();if(requested)await p.goto(requested,{waitUntil:"domcontentloaded",timeout:30000});const first=await snapshotCurrent();await p.waitForTimeout(400);const second=await snapshotCurrent();const digest_match=first.snapshot_digest===second.snapshot_digest;res.json({ok:true,halted:true,digest_match,first_digest:first.snapshot_digest,second_digest:second.snapshot_digest,final_url:second.final_url,title:second.title,authenticated_state:await chatgptState()});}catch(e){res.status(400).json({ok:false,error:String(e?.message||e)});}});
app.post("/owner-session/start",guard,async(_req,res)=>{try{res.json({ok:true,...await startOwnerSession()});}catch(e){endOwnerSession();res.status(500).json({ok:false,error:String(e?.message||e)});}});
app.get("/owner-session/status",guard,(_req,res)=>res.json({ok:true,active:Boolean(ownerSession),expires_at:ownerSession?new Date(ownerSession.expiresAt).toISOString():null}));
app.post("/owner-session/finish",guard,(_req,res)=>{endOwnerSession();res.json({ok:true,finished:true});});
app.get("/owner-browser/session",(req,res)=>{const token=String(req.query.token||"");if(!ownerSession||token!==ownerSession.sessionToken||Date.now()>ownerSession.expiresAt)return res.status(401).send("Invalid or expired browser session.");res.cookie("rmf_browser_view",token,{httpOnly:true,secure:true,sameSite:"lax",path:"/owner-browser",maxAge:15*60*1000});res.redirect("/owner-browser/vnc.html?autoconnect=true&resize=scale&path=owner-browser/websockify");});
app.use("/owner-browser",(req,res)=>{if(!viewerValid(req))return res.status(401).send("Temporary browser login session is not active.");req.url=req.url.replace(/^\/owner-browser/,"")||"/";proxy.web(req,res);});
server.on("upgrade",(req,socket,head)=>{if(!req.url?.startsWith("/owner-browser/")){socket.destroy();return;}const raw=String(req.headers.cookie||"");const cookies=Object.fromEntries(raw.split(";").map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf("=");return[decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}));if(!ownerSession||cookies.rmf_browser_view!==ownerSession.sessionToken||Date.now()>ownerSession.expiresAt){socket.destroy();return;}req.url=req.url.replace(/^\/owner-browser/,"")||"/";proxy.ws(req,socket,head);});
server.listen(PORT,"0.0.0.0",()=>console.log(`browser runtime listening ${PORT}`));