import { NextRequest, NextResponse } from "next/server";
export async function GET(request: NextRequest) {
 const origin=request.nextUrl.origin;
 const error={type:"object",required:["ok","error"],properties:{ok:{type:"boolean"},error:{type:"string"},message:{type:"string"}}};
 const schema={openapi:"3.1.0",info:{title:"Rate My Face Actions API",version:"2.4.0",description:"Rate My Face persistent personal network: free product acquisition plus Stripe-credit-funded cross-session profile, history, recommendations, feedback and reports."},servers:[{url:origin}],security:[{rateMyFaceOAuth:[]}],paths:{
  "/api/product":{post:{operationId:"searchProduct",summary:"FREE — get one Amazon recommendation link",requestBody:{required:true,content:{"application/json":{schema:{$ref:"#/components/schemas/ProductRequest"}}}},responses:{"200":{description:"Amazon result",content:{"application/json":{schema:{$ref:"#/components/schemas/ProductResponse"}}}}}}},
  "/api/billing/entitlements":{get:{operationId:"getEntitlements",summary:"PAYMENT-INFRASTRUCTURE — get entitlements and credit balance",responses:{"200":{description:"Access and balance"}}}},
  "/api/billing/credits/checkout":{post:{operationId:"createCreditCheckoutSession",summary:"PAYMENT-INFRASTRUCTURE — buy 100 Rate My Face credits",description:"Stripe-hosted one-time checkout; credits are granted only after verified webhook.",responses:{"200":{description:"Checkout URL"},"503":{description:"Stripe not configured"}}}},
  "/api/personal":{get:{operationId:"getPersonalNetwork",summary:"PAID/METERED — cross-session profile/history/saved items/connections (1 credit; report 5)",parameters:[{name:"mode",in:"query",schema:{type:"string",enum:["profile","history","saved","connections","report"],default:"profile"}},{name:"limit",in:"query",schema:{type:"integer",minimum:1,maximum:50,default:20}}],responses:{"200":{description:"Persistent personal network data"},"402":{description:"Credits required",content:{"application/json":{schema:{$ref:"#/components/schemas/CreditsRequiredResponse"}}}}}},post:{operationId:"updatePersonalNetwork",summary:"PAID/METERED — evolve profile, store interaction/recommendation, or feedback (1 credit)",requestBody:{required:true,content:{"application/json":{schema:{$ref:"#/components/schemas/PersonalWriteRequest"}}}},responses:{"200":{description:"Saved persistent state"},"402":{description:"Credits required",content:{"application/json":{schema:{$ref:"#/components/schemas/CreditsRequiredResponse"}}}}}}},
  "/api/memory/context":{get:{operationId:"getUserContext",summary:"PAID/METERED — legacy persistent context (1 credit)",responses:{"200":{description:"Context"},"402":{description:"Credits required"}}},post:{operationId:"saveUserContext",summary:"PAID/METERED — legacy context save (1 credit)",requestBody:{required:true,content:{"application/json":{schema:{$ref:"#/components/schemas/SaveUserContextRequest"}}}},responses:{"200":{description:"Saved"},"402":{description:"Credits required"}}},delete:{operationId:"deleteUserContext",summary:"ACCOUNT/SECURITY — delete stored Rate My Face context",responses:{"200":{description:"Deleted"}}}}
 },components:{schemas:{
 ProductRequest:{type:"object",additionalProperties:false,required:["product_type"],properties:{concern:{type:"string",maxLength:120},product_type:{type:"string",maxLength:120},brand:{type:"string",maxLength:80},budget:{type:"string",maxLength:40},region:{type:"string",enum:["US"]}}},
 ProductResponse:{type:"object",properties:{ok:{type:"boolean"},link_type:{type:"string"},asin:{type:["string","null"]},title:{type:["string","null"]},affiliate_url:{type:"string",format:"uri"},partner_tag:{type:"string"},marketplace:{type:"string"}}},
 SaveUserContextRequest:{type:"object",required:["consent_personalization","context"],properties:{consent_personalization:{type:"boolean",const:true},context:{type:"object",additionalProperties:true,properties:{}}}},
 PersonalWriteRequest:{type:"object",required:["operation"],properties:{operation:{type:"string",enum:["update_profile","save_interaction","save_recommendation","recommendation_feedback"]},profile:{type:"object",additionalProperties:true,properties:{}},kind:{type:"string",maxLength:80},summary:{type:"string",maxLength:1000},data:{type:"object",additionalProperties:true,properties:{}},item_type:{type:"string",maxLength:80},title:{type:"string",maxLength:300},url:{type:"string",format:"uri"},recommendation_id:{type:"integer"},feedback:{type:"string",maxLength:200}}},
 CreditsRequiredResponse:{type:"object",required:["ok","error","required_credits","balance","checkout_action"],properties:{ok:{type:"boolean",const:false},error:{type:"string",const:"credits_required"},required_credits:{type:"integer"},balance:{type:"integer"},checkout_action:{type:"string",const:"createCreditCheckoutSession"}}},ErrorResponse:error
 },securitySchemes:{rateMyFaceOAuth:{type:"oauth2",flows:{authorizationCode:{authorizationUrl:`${origin}/oauth/authorize`,tokenUrl:`${origin}/oauth/token`,scopes:{profile:"Use the signed-in Rate My Face account for personalization and billing"}}}}}}};
 return NextResponse.json(schema,{headers:{"Cache-Control":"no-store"}});
}
