import { NextRequest, NextResponse } from "next/server";
export async function GET(request: NextRequest) {
 const origin=request.nextUrl.origin;
 const error={type:"object",required:["ok","error"],properties:{ok:{type:"boolean"},error:{type:"string"},message:{type:"string"}}};
 const schema={openapi:"3.1.0",info:{title:"Rate My Face Actions API",version:"2.3.0",description:"OAuth-authenticated Rate My Face Actions with free acquisition features and Stripe-funded metered credits for advanced persistent Actions."},servers:[{url:origin}],security:[{rateMyFaceOAuth:[]}],paths:{
  "/api/product":{post:{operationId:"searchProduct",summary:"FREE — get one Amazon recommendation link",requestBody:{required:true,content:{"application/json":{schema:{$ref:"#/components/schemas/ProductRequest"}}}},responses:{"200":{description:"Amazon result",content:{"application/json":{schema:{$ref:"#/components/schemas/ProductResponse"}}}},"401":{description:"OAuth required",content:{"application/json":{schema:{$ref:"#/components/schemas/ErrorResponse"}}}}}}},
  "/api/billing/entitlements":{get:{operationId:"getEntitlements",summary:"PAYMENT-INFRASTRUCTURE — get plan, entitlements and credit balance",responses:{"200":{description:"Access and balance",content:{"application/json":{schema:{$ref:"#/components/schemas/EntitlementResponse"}}}},"401":{description:"OAuth required",content:{"application/json":{schema:{$ref:"#/components/schemas/ErrorResponse"}}}}}}},
  "/api/billing/credits/checkout":{post:{operationId:"createCreditCheckoutSession",summary:"PAYMENT-INFRASTRUCTURE — buy a Rate My Face credit pack",description:"Create Stripe-hosted one-time checkout. Return checkout_url unchanged. Credits are granted only after a verified Stripe webhook.",responses:{"200":{description:"Credit checkout",content:{"application/json":{schema:{$ref:"#/components/schemas/CreditCheckoutResponse"}}}},"401":{description:"OAuth required",content:{"application/json":{schema:{$ref:"#/components/schemas/ErrorResponse"}}}},"503":{description:"Stripe credit price not configured",content:{"application/json":{schema:{$ref:"#/components/schemas/ErrorResponse"}}}}}}},
  "/api/billing/checkout":{post:{operationId:"createCheckoutSession",summary:"PAYMENT-INFRASTRUCTURE — optional premium subscription checkout",responses:{"200":{description:"Subscription checkout",content:{"application/json":{schema:{$ref:"#/components/schemas/CheckoutResponse"}}}},"401":{description:"OAuth required",content:{"application/json":{schema:{$ref:"#/components/schemas/ErrorResponse"}}}},"503":{description:"Not configured",content:{"application/json":{schema:{$ref:"#/components/schemas/ErrorResponse"}}}}}}},
  "/api/billing/portal":{post:{operationId:"createBillingPortalSession",summary:"PAYMENT-INFRASTRUCTURE — manage Stripe billing",responses:{"200":{description:"Portal URL",content:{"application/json":{schema:{$ref:"#/components/schemas/PortalResponse"}}}},"401":{description:"OAuth required",content:{"application/json":{schema:{$ref:"#/components/schemas/ErrorResponse"}}}}}}},
  "/api/memory/context":{get:{operationId:"getUserContext",summary:"PAID/METERED — retrieve persistent context (1 credit)",responses:{"200":{description:"Context",content:{"application/json":{schema:{$ref:"#/components/schemas/UserContextResponse"}}}},"402":{description:"Credits required",content:{"application/json":{schema:{$ref:"#/components/schemas/CreditsRequiredResponse"}}}},"401":{description:"OAuth required",content:{"application/json":{schema:{$ref:"#/components/schemas/ErrorResponse"}}}}}},post:{operationId:"saveUserContext",summary:"PAID/METERED — save persistent context (1 credit)",requestBody:{required:true,content:{"application/json":{schema:{$ref:"#/components/schemas/SaveUserContextRequest"}}}},responses:{"200":{description:"Saved",content:{"application/json":{schema:{$ref:"#/components/schemas/MutationResponse"}}}},"402":{description:"Credits required",content:{"application/json":{schema:{$ref:"#/components/schemas/CreditsRequiredResponse"}}}},"401":{description:"OAuth required",content:{"application/json":{schema:{$ref:"#/components/schemas/ErrorResponse"}}}}}},delete:{operationId:"deleteUserContext",summary:"ACCOUNT/SECURITY — delete stored context (always free)",responses:{"200":{description:"Deleted",content:{"application/json":{schema:{$ref:"#/components/schemas/MutationResponse"}}}},"401":{description:"OAuth required",content:{"application/json":{schema:{$ref:"#/components/schemas/ErrorResponse"}}}}}}}
 },components:{schemas:{
 ProductRequest:{type:"object",additionalProperties:false,required:["product_type"],properties:{concern:{type:"string",maxLength:120},product_type:{type:"string",maxLength:120},brand:{type:"string",maxLength:80},budget:{type:"string",maxLength:40},region:{type:"string",enum:["US"]}}},
 ProductResponse:{type:"object",required:["ok","link_type","affiliate_url","partner_tag","marketplace"],properties:{ok:{type:"boolean"},link_type:{type:"string"},asin:{type:["string","null"]},title:{type:["string","null"]},affiliate_url:{type:"string",format:"uri"},partner_tag:{type:"string"},marketplace:{type:"string"}}},
 SaveUserContextRequest:{type:"object",additionalProperties:false,required:["consent_personalization","context"],properties:{consent_personalization:{type:"boolean",const:true},context:{type:"object",additionalProperties:true,properties:{}}}},
 UserContextResponse:{type:"object",required:["ok","found"],properties:{ok:{type:"boolean"},found:{type:"boolean"},context:{type:["object","null"],additionalProperties:true,properties:{}},credits_charged:{type:"integer"},credits_remaining:{type:"integer"}}},
 MutationResponse:{type:"object",required:["ok"],properties:{ok:{type:"boolean"},saved:{type:"boolean"},deleted:{type:"boolean"},credits_charged:{type:"integer"},credits_remaining:{type:"integer"}}},
 EntitlementResponse:{type:"object",required:["ok","plan","premium","features","credits"],properties:{ok:{type:"boolean"},plan:{type:"string"},premium:{type:"boolean"},features:{type:"array",items:{type:"string"}},credits:{type:"integer"},subscription_status:{type:["string","null"]}}},
 CreditCheckoutResponse:{type:"object",required:["ok","checkout_url","session_id","credits"],properties:{ok:{type:"boolean"},checkout_url:{type:"string",format:"uri"},session_id:{type:"string"},credits:{type:"integer"}}},
 CheckoutResponse:{type:"object",required:["ok","checkout_url","session_id","plan"],properties:{ok:{type:"boolean"},checkout_url:{type:"string",format:"uri"},session_id:{type:"string"},plan:{type:"string"}}},PortalResponse:{type:"object",required:["ok","portal_url"],properties:{ok:{type:"boolean"},portal_url:{type:"string",format:"uri"}}},
 CreditsRequiredResponse:{type:"object",required:["ok","error","required_credits","balance","checkout_action"],properties:{ok:{type:"boolean",const:false},error:{type:"string",const:"credits_required"},message:{type:"string"},required_credits:{type:"integer"},balance:{type:"integer"},checkout_action:{type:"string",const:"createCreditCheckoutSession"}}},ErrorResponse:error
 },securitySchemes:{rateMyFaceOAuth:{type:"oauth2",flows:{authorizationCode:{authorizationUrl:`${origin}/oauth/authorize`,tokenUrl:`${origin}/oauth/token`,scopes:{profile:"Use the signed-in Rate My Face account for personalization and billing"}}}}}}};
 return NextResponse.json(schema,{headers:{"Cache-Control":"no-store"}});
}
